"""Adiciona campos de reset de senha para Usuario

Revision ID: 2fef59c9d87f
Revises: 
Create Date: 2025-09-22 16:40:51.579372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fef59c9d87f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_questoes_id'), table_name='questoes')
    op.drop_table('questoes')
    op.drop_index(op.f('ix_historicos_simulados_id'), table_name='historicos_simulados')
    op.drop_table('historicos_simulados')
    op.drop_index(op.f('ix_estudos_diarios_id'), table_name='estudos_diarios')
    op.drop_table('estudos_diarios')
    op.drop_index(op.f('ix_orgaos_id'), table_name='orgaos')
    op.drop_index(op.f('ix_orgaos_label'), table_name='orgaos')
    op.drop_table('orgaos')
    op.drop_index(op.f('ix_bancas_id'), table_name='bancas')
    op.drop_index(op.f('ix_bancas_label'), table_name='bancas')
    op.drop_table('bancas')
    op.drop_index(op.f('ix_historicos_id'), table_name='historicos')
    op.drop_table('historicos')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_instituicoes_id'), table_name='instituicoes')
    op.drop_index(op.f('ix_instituicoes_label'), table_name='instituicoes')
    op.drop_table('instituicoes')
    op.drop_index(op.f('ix_resolucoes_questoes_simulados_id'), table_name='resolucoes_questoes_simulados')
    op.drop_table('resolucoes_questoes_simulados')
    op.drop_index(op.f('ix_alternativas_id'), table_name='alternativas')
    op.drop_table('alternativas')
    op.drop_index(op.f('ix_cronogramas_id'), table_name='cronogramas')
    op.drop_table('cronogramas')
    op.drop_index(op.f('ix_disciplinas_id'), table_name='disciplinas')
    op.drop_index(op.f('ix_disciplinas_label'), table_name='disciplinas')
    op.drop_table('disciplinas')
    op.drop_index(op.f('ix_comentarios_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_resolucoes_questoes_id'), table_name='resolucoes_questoes')
    op.drop_table('resolucoes_questoes')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resolucoes_questoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_resolucao', sa.DATETIME(), nullable=False),
    sa.Column('is_certa', sa.BOOLEAN(), nullable=False),
    sa.Column('historico_id', sa.INTEGER(), nullable=False),
    sa.Column('questao_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['historico_id'], ['historicos.id'], ),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolucoes_questoes_id'), 'resolucoes_questoes', ['id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comentario', sa.VARCHAR(), nullable=True),
    sa.Column('data_comentario', sa.DATETIME(), nullable=True),
    sa.Column('id_usuario', sa.INTEGER(), nullable=True),
    sa.Column('id_questao', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_questao'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_id'), 'comentarios', ['id'], unique=False)
    op.create_table('disciplinas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplinas_label'), 'disciplinas', ['label'], unique=False)
    op.create_index(op.f('ix_disciplinas_id'), 'disciplinas', ['id'], unique=False)
    op.create_table('cronogramas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronogramas_id'), 'cronogramas', ['id'], unique=False)
    op.create_table('alternativas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('descricao', sa.VARCHAR(), nullable=True),
    sa.Column('explicacao', sa.VARCHAR(), nullable=True),
    sa.Column('is_correta', sa.BOOLEAN(), nullable=True),
    sa.Column('id_questao', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_questao'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alternativas_id'), 'alternativas', ['id'], unique=False)
    op.create_table('resolucoes_questoes_simulados',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('historico_simulado_id', sa.INTEGER(), nullable=False),
    sa.Column('questao_id', sa.INTEGER(), nullable=False),
    sa.Column('correta', sa.BOOLEAN(), nullable=False),
    sa.Column('data_resolucao', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['historico_simulado_id'], ['historicos_simulados.id'], ),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolucoes_questoes_simulados_id'), 'resolucoes_questoes_simulados', ['id'], unique=False)
    op.create_table('instituicoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instituicoes_label'), 'instituicoes', ['label'], unique=False)
    op.create_index(op.f('ix_instituicoes_id'), 'instituicoes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cpf', sa.VARCHAR(), nullable=False),
    sa.Column('nome', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('avatar', sa.VARCHAR(), nullable=True),
    sa.Column('senha', sa.VARCHAR(), nullable=False),
    sa.Column('data_criacao', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=1)
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=1)
    op.create_table('historicos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dias_sequencia', sa.INTEGER(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historicos_id'), 'historicos', ['id'], unique=False)
    op.create_table('bancas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bancas_label'), 'bancas', ['label'], unique=False)
    op.create_index(op.f('ix_bancas_id'), 'bancas', ['id'], unique=False)
    op.create_table('orgaos',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('label', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orgaos_label'), 'orgaos', ['label'], unique=False)
    op.create_index(op.f('ix_orgaos_id'), 'orgaos', ['id'], unique=False)
    op.create_table('estudos_diarios',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('hora_inicio', sa.TIME(), nullable=False),
    sa.Column('hora_fim', sa.TIME(), nullable=False),
    sa.Column('concluido', sa.BOOLEAN(), nullable=True),
    sa.Column('dia_da_semana', sa.VARCHAR(length=7), nullable=False),
    sa.Column('id_disciplina', sa.INTEGER(), nullable=True),
    sa.Column('id_cronograma', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_cronograma'], ['cronogramas.id'], ),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudos_diarios_id'), 'estudos_diarios', ['id'], unique=False)
    op.create_table('historicos_simulados',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('data_resolucao', sa.DATETIME(), nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historicos_simulados_id'), 'historicos_simulados', ['id'], unique=False)
    op.create_table('questoes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('enunciado', sa.VARCHAR(), nullable=True),
    sa.Column('ja_respondeu', sa.BOOLEAN(), nullable=True),
    sa.Column('id_disciplina', sa.INTEGER(), nullable=True),
    sa.Column('dificuldade', sa.VARCHAR(length=7), nullable=False),
    sa.Column('id_orgao', sa.INTEGER(), nullable=True),
    sa.Column('id_instituicao', sa.INTEGER(), nullable=True),
    sa.Column('id_banca', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id_banca'], ['bancas.id'], ),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['id_instituicao'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['id_orgao'], ['orgaos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questoes_id'), 'questoes', ['id'], unique=False)
    # ### end Alembic commands ###
