"""Coluna valor pagamento

Revision ID: 013a1dd4cbfe
Revises: 75d21ee35bf9
Create Date: 2025-11-03 15:54:35.650107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '013a1dd4cbfe'
down_revision: Union[str, Sequence[str], None] = '75d21ee35bf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamentos', sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pagamentos', 'valor')
    # ### end Alembic commands ###
