"""joined table inheritance pagamento

Revision ID: 06afb43eedcd
Revises: 97337850fccf
Create Date: 2025-10-29 14:16:12.818604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06afb43eedcd'
down_revision: Union[str, Sequence[str], None] = '97337850fccf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pagamentos', 'id_plano',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('pagamentos', 'codigo_barras')
    op.drop_column('pagamentos', 'chave_pix')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamentos', sa.Column('chave_pix', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('pagamentos', sa.Column('codigo_barras', sa.VARCHAR(length=48), autoincrement=False, nullable=True))
    op.alter_column('pagamentos', 'id_plano',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
