"""Adiciona campo de login google torna campos opcionais

Revision ID: 1c69a32d208d
Revises: a1b2c3d4e5f6
Create Date: 2025-11-24 20:52:19.171374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c69a32d208d'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuarios', sa.Column('id_google', sa.String(), nullable=True))
    op.alter_column('usuarios', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('usuarios', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'usuarios', ['id_google'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', type_='unique')
    op.alter_column('usuarios', 'senha',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('usuarios', 'cpf',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('usuarios', 'id_google')
    # ### end Alembic commands ###
