"""Migracao inicial de todas as tabelas

Revision ID: 2f3a9becb9fa
Revises: 
Create Date: 2025-11-05 13:27:10.555142

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f3a9becb9fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bancas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bancas_id'), 'bancas', ['id'], unique=False)
    op.create_index(op.f('ix_bancas_label'), 'bancas', ['label'], unique=False)
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplinas_id'), 'disciplinas', ['id'], unique=False)
    op.create_index(op.f('ix_disciplinas_label'), 'disciplinas', ['label'], unique=False)
    op.create_table('instituicoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_instituicoes_id'), 'instituicoes', ['id'], unique=False)
    op.create_index(op.f('ix_instituicoes_label'), 'instituicoes', ['label'], unique=False)
    op.create_table('objetivos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('area', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objetivos_id'), 'objetivos', ['id'], unique=False)
    op.create_table('orgaos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orgaos_id'), 'orgaos', ['id'], unique=False)
    op.create_index(op.f('ix_orgaos_label'), 'orgaos', ['label'], unique=False)
    op.create_table('planos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('beneficios', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planos_id'), 'planos', ['id'], unique=False)
    op.create_table('questoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enunciado', sa.String(), nullable=True),
    sa.Column('ja_respondeu', sa.Boolean(), nullable=True),
    sa.Column('id_disciplina', sa.Integer(), nullable=False),
    sa.Column('dificuldade', sa.Enum('FACIL', 'MEDIO', 'DIFICIL', name='dificuldadeenum'), nullable=False),
    sa.Column('id_orgao', sa.Integer(), nullable=False),
    sa.Column('id_instituicao', sa.Integer(), nullable=False),
    sa.Column('id_banca', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_banca'], ['bancas.id'], ),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplinas.id'], ),
    sa.ForeignKeyConstraint(['id_instituicao'], ['instituicoes.id'], ),
    sa.ForeignKeyConstraint(['id_orgao'], ['orgaos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questoes_id'), 'questoes', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_objetivo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_objetivo'], ['objetivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_cpf'), 'usuarios', ['cpf'], unique=True)
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('alternativas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('explicacao', sa.String(), nullable=True),
    sa.Column('is_correta', sa.Boolean(), nullable=True),
    sa.Column('id_questao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_questao'], ['questoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alternativas_id'), 'alternativas', ['id'], unique=False)
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.String(), nullable=True),
    sa.Column('data_comentario', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_questao', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_questao'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comentarios_id'), 'comentarios', ['id'], unique=False)
    op.create_table('cronogramas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cronogramas_id'), 'cronogramas', ['id'], unique=False)
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_plano', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_plano'], ['planos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resolucoes_questoes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('data_resolucao', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_certa', sa.Boolean(), nullable=False),
    sa.Column('questao_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resolucoes_questoes_id'), 'resolucoes_questoes', ['id'], unique=False)
    op.create_table('estudos_diarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('concluido', sa.Boolean(), nullable=True),
    sa.Column('dia_da_semana', sa.Enum('DOMINGO', 'SEGUNDA', 'TERCA', 'QUARTA', 'QUINTA', 'SEXTA', 'SABADO', name='diadasemanaenum'), nullable=False),
    sa.Column('id_disciplina', sa.Integer(), nullable=True),
    sa.Column('id_cronograma', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cronograma'], ['cronogramas.id'], ),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estudos_diarios_id'), 'estudos_diarios', ['id'], unique=False)
    op.create_table('pagamentos_boleto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_barras', sa.String(length=48), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pagamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos_cartao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(length=16), nullable=False),
    sa.Column('validade', sa.String(length=5), nullable=False),
    sa.Column('nome_titular', sa.String(length=100), nullable=False),
    sa.Column('codigo_seguranca', sa.String(length=4), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pagamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos_pix',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave_pix', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pagamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos_pix')
    op.drop_table('pagamentos_cartao')
    op.drop_table('pagamentos_boleto')
    op.drop_index(op.f('ix_estudos_diarios_id'), table_name='estudos_diarios')
    op.drop_table('estudos_diarios')
    op.drop_index(op.f('ix_resolucoes_questoes_id'), table_name='resolucoes_questoes')
    op.drop_table('resolucoes_questoes')
    op.drop_table('pagamentos')
    op.drop_index(op.f('ix_cronogramas_id'), table_name='cronogramas')
    op.drop_table('cronogramas')
    op.drop_index(op.f('ix_comentarios_id'), table_name='comentarios')
    op.drop_table('comentarios')
    op.drop_index(op.f('ix_alternativas_id'), table_name='alternativas')
    op.drop_table('alternativas')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_cpf'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_questoes_id'), table_name='questoes')
    op.drop_table('questoes')
    op.drop_index(op.f('ix_planos_id'), table_name='planos')
    op.drop_table('planos')
    op.drop_index(op.f('ix_orgaos_label'), table_name='orgaos')
    op.drop_index(op.f('ix_orgaos_id'), table_name='orgaos')
    op.drop_table('orgaos')
    op.drop_index(op.f('ix_objetivos_id'), table_name='objetivos')
    op.drop_table('objetivos')
    op.drop_index(op.f('ix_instituicoes_label'), table_name='instituicoes')
    op.drop_index(op.f('ix_instituicoes_id'), table_name='instituicoes')
    op.drop_table('instituicoes')
    op.drop_index(op.f('ix_disciplinas_label'), table_name='disciplinas')
    op.drop_index(op.f('ix_disciplinas_id'), table_name='disciplinas')
    op.drop_table('disciplinas')
    op.drop_index(op.f('ix_bancas_label'), table_name='bancas')
    op.drop_index(op.f('ix_bancas_id'), table_name='bancas')
    op.drop_table('bancas')
    # ### end Alembic commands ###
