"""Coluna data pagamento e relacionamento usuario

Revision ID: 3aefc716e32d
Revises: 013a1dd4cbfe
Create Date: 2025-11-03 18:12:59.851307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3aefc716e32d'
down_revision: Union[str, Sequence[str], None] = '013a1dd4cbfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pagamentos', sa.Column('data_pagamento', sa.DateTime(), nullable=True))
    op.add_column('pagamentos', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'pagamentos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pagamentos', type_='foreignkey')
    op.drop_column('pagamentos', 'usuario_id')
    op.drop_column('pagamentos', 'data_pagamento')
    # ### end Alembic commands ###
