"""Remove modelos

Revision ID: 6f2c6ac0ee2e
Revises: 06afb43eedcd
Create Date: 2025-11-03 15:08:21.010239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f2c6ac0ee2e'
down_revision: Union[str, Sequence[str], None] = '06afb43eedcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resolucoes_questoes_simulados_id'), table_name='resolucoes_questoes_simulados')
    op.drop_table('resolucoes_questoes_simulados')
    op.drop_index(op.f('ix_historicos_simulados_id'), table_name='historicos_simulados')
    op.drop_table('historicos_simulados')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historicos_simulados',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('historicos_simulados_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('data_resolucao', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('usuario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name='historicos_simulados_usuario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='historicos_simulados_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_historicos_simulados_id'), 'historicos_simulados', ['id'], unique=False)
    op.create_table('resolucoes_questoes_simulados',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('historico_simulado_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('questao_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correta', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('data_resolucao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['historico_simulado_id'], ['historicos_simulados.id'], name=op.f('resolucoes_questoes_simulados_historico_simulado_id_fkey')),
    sa.ForeignKeyConstraint(['questao_id'], ['questoes.id'], name=op.f('resolucoes_questoes_simulados_questao_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('resolucoes_questoes_simulados_pkey'))
    )
    op.create_index(op.f('ix_resolucoes_questoes_simulados_id'), 'resolucoes_questoes_simulados', ['id'], unique=False)
    # ### end Alembic commands ###
