"""Modelo de cartao

Revision ID: 75d21ee35bf9
Revises: 6f2c6ac0ee2e
Create Date: 2025-11-03 15:32:43.112669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75d21ee35bf9'
down_revision: Union[str, Sequence[str], None] = '6f2c6ac0ee2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos_cartao')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pagamentos_cartao',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('validade', sa.VARCHAR(length=5), autoincrement=False, nullable=False),
    sa.Column('nome_titular', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('codigo_seguranca', sa.VARCHAR(length=4), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['id'], ['pagamentos.id'], name=op.f('pagamentos_cartao_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('pagamentos_cartao_pkey'))
    )
    # ### end Alembic commands ###
